from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from sqlalchemy.orm import Session
from typing import List
import logging
import os
from datetime import datetime

from .. import database, models, schemas, crud
from ..services.ai_analyzer import ContentAnalyzer

router = APIRouter()
logger = logging.getLogger(__name__)

@router.post("/{video_id}/analyze", response_model=schemas.ScriptAnalysis)
def analyze_script(
    video_id: int, 
    background_tasks: BackgroundTasks,
    db: Session = Depends(database.get_db)
):
    video = crud.get_video(db, video_id)
    if not video:
        raise HTTPException(status_code=404, detail="Video not found")

    # 1. Check if analysis already exists
    if video.script_analysis:
        return video.script_analysis

    # 2. Get Subtitles
    import os
    subtitle_path = None
    if video.file_path:
        base, _ = os.path.splitext(video.file_path)
        # Try common subtitle formats
        for ext in ['.ko.vtt', '.en.vtt', '.vtt', '.srt']:
            if os.path.exists(base + ext):
                subtitle_path = base + ext
                break
    
    content = ""
    if subtitle_path:
        with open(subtitle_path, 'r', encoding='utf-8') as f:
            content = f.read()
    else:
        # If no subtitle file, maybe use description or fail?
        # Ideally we need script.
        if not video.is_script_only: 
             raise HTTPException(status_code=400, detail="No subtitle file found for analysis.")
        
        # For Script Only mode, maybe the content is stored elsewhere? 
        # For now assume file_path points to a text file?
        if video.file_path and video.file_path.endswith('.txt'):
             with open(video.file_path, 'r', encoding='utf-8') as f:
                content = f.read()

    if not content:
        raise HTTPException(status_code=400, detail="Script content is empty.")

    # 3. Perform Analysis
    settings = db.query(models.Settings).first()
    if not settings:
         raise HTTPException(status_code=500, detail="Settings not found")

    analyzer = ContentAnalyzer(db, settings)
    try:
        # If analysis doesn't exist, generate it
        if not video.script_analysis:
            analysis_data = analyzer.analyze_script(video, content)
            analysis_data.script_content = content
            db_analysis = models.ScriptAnalysis(**analysis_data.dict())
            db.add(db_analysis)
            db.commit()
            db.refresh(db_analysis)
        else:
            db_analysis = video.script_analysis

        # [ALWAYS] Ensure Operation Workspace & Artifacts
        try:
            from ..utils.path_utils import ensure_project_workspace
            import json
            
            workspace_root = ensure_project_workspace(video.id, video.title)
            
            # Artifact 1: analysis.json (Sync from DB)
            analysis_dict = {c.name: getattr(db_analysis, c.name) for c in db_analysis.__table__.columns if c.name not in ['id', 'video_id', 'created_at', 'updated_at']}
            with open(os.path.join(workspace_root, "analysis.json"), "w", encoding="utf-8") as f:
                json.dump(analysis_dict, f, indent=2, ensure_ascii=False)
            
            # Artifact 2: original_script.txt
            with open(os.path.join(workspace_root, "original_script.txt"), "w", encoding="utf-8") as f:
                f.write(content)
                
            # Artifact 3: strategy_brief.md (Professional Document)
            brief = f"""# Strategic Mission Brief: {video.title}
## Overview
- **Viral Score:** {db_analysis.viral_score}/100
- **Tone:** {db_analysis.tone}
- **Sentiment:** {db_analysis.sentiment_label} ({db_analysis.sentiment_score})

## Summary
### One-Line Hook
> {db_analysis.summary_one_line}

### Context
{db_analysis.summary_three_lines}

## Strategic Components
### Core Keywords
{', '.join(db_analysis.keywords)}

## Intelligence Analysis
- **Audience Reaction:** {json.dumps(db_analysis.audience_reaction, indent=2, ensure_ascii=False)}
- **Structure Breakdown:** {json.dumps(db_analysis.structure_breakdown, indent=2, ensure_ascii=False)}

---
*Generated by Elite Command Studio v8.0 Sovereign Intel*
"""
            with open(os.path.join(workspace_root, "strategy_brief.md"), "w", encoding="utf-8") as f:
                f.write(brief)
                
            logger.info(f"[OK] Operation Workspace synchronized at: {workspace_root}")
            
            # Update video metadata
            if video.metadata_json is None: video.metadata_json = {}
            video.metadata_json["workspace_path"] = workspace_root
            db.commit()

        except Exception as workspace_err:
            logger.error(f"Failed to synchronize workspace: {workspace_err}")

        return db_analysis
        
    except Exception as e:
        logger.error(f"Analysis failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/{video_id}/analysis", response_model=schemas.ScriptAnalysis)
def get_analysis(video_id: int, db: Session = Depends(database.get_db)):
    video = crud.get_video(db, video_id)
    if not video:
        raise HTTPException(status_code=404, detail="Video not found")
        
    if not video.script_analysis:
        raise HTTPException(status_code=404, detail="Analysis not found. Please run analysis first.")
        
    return video.script_analysis

@router.post("/rewrite", response_model=schemas.ScriptGenerationResponse)
def rewrite_script(
    request: schemas.ScriptRewriteRequest,
    db: Session = Depends(database.get_db)
):
    settings = db.query(models.Settings).first()
    if not settings:
         raise HTTPException(status_code=500, detail="Settings not found")

    provider = request.provider or settings.script_analysis_provider
    model = request.model or settings.script_analysis_model

    analyzer = ContentAnalyzer(db, settings)
    try:
        rewritten_script = analyzer.rewrite_script(
            original_script=request.original_script, 
            instruction=request.instruction,
            provider=provider,
            model=model,
            tempo_percentage=request.tempo_percentage or 100
        )
        
        # [NEW] Save refined script to workspace if it exists
        try:
            video = db.query(models.Video).filter(models.Video.id == request.video_id).first() if hasattr(request, "video_id") else None
            # Note: schemas.ScriptRewriteRequest might not have video_id, let's check.
            # If not, we might need to add it or find the video differently.
            
            if video and video.metadata_json and "workspace_path" in video.metadata_json:
                workspace_root = video.metadata_json["workspace_path"]
                if os.path.exists(workspace_root):
                    with open(os.path.join(workspace_root, "refined_script.txt"), "w", encoding="utf-8") as f:
                        f.write(rewritten_script)
                    
                    # Also append/update the markdown brief
                    with open(os.path.join(workspace_root, "strategy_brief.md"), "a", encoding="utf-8") as f:
                        f.write(f"\n\n## Refined Narrative\n> {rewritten_script}\n\n*Updated via Elite Refinement Engine*")
                    
                    logger.info(f"[OK] Refined script saved to workspace: {workspace_root}")
        except Exception as e:
            logger.warning(f"Could not save refined script to workspace: {e}")

        return schemas.ScriptGenerationResponse(
            script=rewritten_script,
            model_used=model
        )
        
    except Exception as e:
        logger.error(f"Rewrite failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))
@router.post("/{video_id}/save")
def save_script(
    video_id: int,
    request: schemas.ScriptSaveRequest,
    db: Session = Depends(database.get_db)
):
    video = db.query(models.Video).filter(models.Video.id == video_id).first()
    if not video:
        raise HTTPException(status_code=404, detail="Video not found")
        
    if not video.script_analysis:
        # Create empty analysis if it doesn't exist to store script
        db_analysis = models.ScriptAnalysis(
            video_id=video_id,
            script_content=request.script_content,
            viral_score=0,
            summary_one_line="",
            summary_three_lines="",
            sentiment_score=0.0,
            sentiment_label="Neutral",
            tone="Unknown",
            keywords=[],
            hooks=[],
            audience_reaction={},
            structure_breakdown={}
        )
        db.add(db_analysis)
    else:
        video.script_analysis.script_content = request.script_content
        video.script_analysis.updated_at = datetime.now()
        
    db.commit()
     # [ALWAYS] Ensure Workspace & Sync Script
    try:
        from ..utils.path_utils import ensure_project_workspace
        import shutil

        workspace_root = ensure_project_workspace(video.id, video.title)
        
        # Save script to refined_script.txt (Current State)
        with open(os.path.join(workspace_root, "refined_script.txt"), "w", encoding="utf-8") as f:
            f.write(request.script_content)
        
        # Update metadata if missing
        if not video.metadata_json or "workspace_path" not in video.metadata_json:
            if video.metadata_json is None: video.metadata_json = {}
            video.metadata_json["workspace_path"] = workspace_root
            db.commit()

        logger.info(f"[OK] Script synced to workspace: {workspace_root}")
    except Exception as e:
        logger.warning(f"Failed to sync script to workspace: {e}")

    return {"status": "success", "message": "Script saved successfully"}

@router.post("/{video_id}/persist-genesis")
def persist_genesis(
    video_id: int,
    request: schemas.GenesisPersistRequest,
    db: Session = Depends(database.get_db)
):
    """
    Moves generated genesis assets (audio, srt) from temp storage to project workspace.
    """
    video = db.query(models.Video).filter(models.Video.id == video_id).first()
    if not video:
        raise HTTPException(status_code=404, detail="Video not found")
    
    from ..utils.path_utils import ensure_project_workspace
    import shutil
    
    workspace_root = ensure_project_workspace(video.id, video.title)
    
    results = {}
    
    # 1. Persist Audio
    if request.audio_path and os.path.exists(request.audio_path):
        target_audio = os.path.join(workspace_root, "genesis_voice.mp3")
        shutil.copy2(request.audio_path, target_audio)
        results["audio"] = target_audio
        logger.info(f"[OK] Audio persisted: {target_audio}")
        
    # 2. Persist SRT
    if request.srt_content:
        target_srt = os.path.join(workspace_root, "genesis_subtitles.srt")
        with open(target_srt, "w", encoding="utf-8") as f:
            f.write(request.srt_content)
        results["srt"] = target_srt
        logger.info(f"[OK] SRT persisted: {target_srt}")

    return {"status": "success", "assets": results}

